#ifndef _RST_STATUS_CODE_H
#define _RST_STATUS_CODE_H 1

enum RST_StatusCodes 
{
    RST_STATUSCODE_PROCESSING = 102,
    RST_STATUSCODE_OK = 200,
    RST_STATUSCODE_BAD_REQUEST = 400,
    RST_STATUSCODE_UNAUTHORIZED = 401,
    RST_STATUSCODE_FORBIDDEN = 403,
    RST_STATUSCODE_NOT_FOUND = 404
};

#endif